import path from 'path';
import { execSync } from 'child_process';
import pc from 'picocolors';
import { promptProjectOptions, type ProjectOptions } from '../prompts/project.js';
import { writeFile, directoryExists, isDirectoryEmpty, ensureDir } from '../utils/fs.js';
import { createSpinner } from '../utils/spinner.js';
import {
  generatePackageJson,
  generateTsconfig,
  generateConfig,
  generateBalanceProof,
  generateAgeProof,
  generateMinimalCircuit,
  generateCircuitsIndex,
  generateTestScript,
  generateReadme,
  generateGitignore,
} from '../generators/index.js';

interface CliOptions {
  template: string;
  provider: string;
  yes: boolean;
  skipInstall: boolean;
  skipGit: boolean;
}

export async function initCommand(
  projectName: string | undefined,
  options: CliOptions
): Promise<void> {
  let projectOptions: ProjectOptions | null;

  if (options.yes && projectName) {
    // Non-interactive mode with all defaults
    projectOptions = {
      projectName,
      template: options.template,
      provider: options.provider,
      skipInstall: options.skipInstall,
      skipGit: options.skipGit,
    };
  } else {
    projectOptions = await promptProjectOptions({
      projectName,
      template: options.template,
      provider: options.provider,
      skipInstall: options.skipInstall,
      skipGit: options.skipGit,
    });
  }

  if (!projectOptions) {
    console.log(pc.yellow('\nOperation cancelled.'));
    process.exit(0);
  }

  const projectDir = path.resolve(process.cwd(), projectOptions.projectName);

  // Check if directory exists and is not empty
  if (await directoryExists(projectDir)) {
    if (!(await isDirectoryEmpty(projectDir))) {
      console.log(
        pc.red(`\nError: Directory "${projectOptions.projectName}" already exists and is not empty.`)
      );
      process.exit(1);
    }
  }

  console.log();

  // Create project structure
  const spinner = createSpinner('Creating project structure...');
  spinner.start();

  try {
    await createProjectStructure(projectDir, projectOptions);
    spinner.stop(true);
  } catch (error) {
    spinner.stop(false);
    console.error(pc.red('\nFailed to create project structure:'), error);
    process.exit(1);
  }

  // Initialize git
  if (!projectOptions.skipGit) {
    const gitSpinner = createSpinner('Initializing git repository...');
    gitSpinner.start();

    try {
      execSync('git init', { cwd: projectDir, stdio: 'ignore' });
      gitSpinner.stop(true);
    } catch {
      gitSpinner.stop(false);
      console.log(pc.yellow('  Warning: Failed to initialize git repository'));
    }
  }

  // Install dependencies
  if (!projectOptions.skipInstall) {
    const installSpinner = createSpinner('Installing dependencies...');
    installSpinner.start();

    try {
      execSync('npm install', { cwd: projectDir, stdio: 'ignore' });
      installSpinner.stop(true);
    } catch {
      installSpinner.stop(false);
      console.log(pc.yellow('  Warning: Failed to install dependencies. Run "npm install" manually.'));
    }
  }

  // Print success message
  printSuccessMessage(projectOptions);
}

async function createProjectStructure(
  projectDir: string,
  options: ProjectOptions
): Promise<void> {
  // Create directories
  await ensureDir(path.join(projectDir, 'circuits'));
  await ensureDir(path.join(projectDir, 'generated'));
  await ensureDir(path.join(projectDir, 'scripts'));

  // Generate and write files
  const files: Array<[string, string]> = [
    ['package.json', generatePackageJson(options)],
    ['tsconfig.json', generateTsconfig()],
    ['izi-noir.config.ts', generateConfig(options)],
    ['README.md', generateReadme(options)],
    ['.gitignore', generateGitignore()],
    ['scripts/test-proof.ts', generateTestScript(options)],
  ];

  // Add circuit files based on template
  switch (options.template) {
    case 'minimal':
      files.push(['circuits/my-circuit.ts', generateMinimalCircuit()]);
      break;
    case 'balance-proof':
      files.push(['circuits/balance-proof.ts', generateBalanceProof()]);
      break;
    default:
      files.push(['circuits/balance-proof.ts', generateBalanceProof()]);
      files.push(['circuits/age-proof.ts', generateAgeProof()]);
      break;
  }

  // Add circuits index
  files.push(['circuits/index.ts', generateCircuitsIndex(options.template)]);

  // Add placeholder for generated
  files.push([
    'generated/.gitkeep',
    '# This directory contains compiled circuit artifacts\n# Generated by: npm run build\n',
  ]);

  // Write all files
  await Promise.all(
    files.map(([relativePath, content]) =>
      writeFile(path.join(projectDir, relativePath), content)
    )
  );
}

function printSuccessMessage(options: ProjectOptions): void {
  console.log();
  console.log(pc.green('✓') + ' Project created successfully!');
  console.log();
  console.log('Next steps:');
  console.log();
  console.log(pc.cyan(`  cd ${options.projectName}`));

  if (options.skipInstall) {
    console.log(pc.cyan('  npm install'));
  }

  console.log(pc.cyan('  npm run build'));
  console.log(pc.cyan('  npm test'));
  console.log();
  console.log('To start developing:');
  console.log();
  console.log(pc.dim('  1. Edit circuits in circuits/*.ts'));
  console.log(pc.dim('  2. Run "npm run dev" for watch mode'));
  console.log(pc.dim('  3. Test with "npm test"'));
  console.log();
  console.log(
    pc.dim('Learn more: ') + pc.blue('https://github.com/izi-noir/izi-noir')
  );
  console.log();
}
